### ISSUE TITLE
DrawdownPeak function is not exported in 1.5.2

### ISSUE THREAD

**Issue by phongntflixvn** [braverock/PerformanceAnalytics#89]
After upgrading PerformanceAnalytics to 1.5.2, I cannot find function "DrawdownPeak", even though the documentation still showing it

```
> library("PerformanceAnalytics")
Loading required package: xts
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Package PerformanceAnalytics (1.5.2) loaded.
Copyright (c) 2004-2018 Peter Carl and Brian G. Peterson, GPL-2 | GPL-3
https://github.com/braverock/PerformanceAnalytics


Attaching package: ‘PerformanceAnalytics’

The following object is masked from ‘package:graphics’:

    legend

> DrawdownPeak
Error: object 'DrawdownPeak' not found


> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] PerformanceAnalytics_1.5.2 xts_0.10-2                
[3] zoo_1.8-1                 

loaded via a namespace (and not attached):
[1] compiler_3.4.3  tools_3.4.3     grid_3.4.3      lattice_0.20-35
[5] quadprog_1.5-5  tcltk_3.4.3    

```

**Comment by openbmsjsc** [comment]
I think there is a simple mistake to comment out the export

```
diff --git a/R/DrawdownPeak.R b/R/DrawdownPeak.R
index 5c771e5..df44413 100644
--- a/R/DrawdownPeak.R
+++ b/R/DrawdownPeak.R
@@ -9,7 +9,7 @@
 #' @author Matthieu Lestel
 #'
 ###keywords ts multivariate distribution models
-### #' @export
+#' @export DrawdownPeak

```

**Comment by p0bs** [comment]
In the meantime, you can use `PerformanceAnalytics:::DrawdownPeak`

**Comment by braverock** [comment]
now fixed in git v 1.5.2.1, thanks for the reminder that this was still outstanding.

**Comment by apsteinmetz** [comment]
Cran version is still 1.5.2 so docs report function that is not exported.  I am all good with the Github version but Cran version caused me some hair pulling before I found this.  Thanks.

**Comment by braverock** [comment]
we will push a new version to CRAN 'soon', thanks for the reminder.
